export const categories = [
  {
    slug: 'activewear',
    image: '/images/textiles/activewear.jpg',
    cardImage: '/images/textiles/original-thumbnails/activewear.jpg',
    title: 'Activewear',
    tagline: 'Flexible & Comfortable',
    cardDescription: 'High fashion seamless lightweight clothing with extreme durability and elasticity, designed to properly fit the body.',
    description: 'Seamless garment technology lets us produce lightweight, extremely durable and elastic activewear in one continuous process — no cutting or sewing seams, just comfort and freedom of movement.',
    gallery: [
      '/images/textiles/activewear.jpg',
      '/images/textiles/gallery/activewear-2.jpg',
      '/images/textiles/gallery/activewear-3.jpg',
    ],
    productGrid: [
      '/images/textiles/gallery/activewear-grid/product-1.jpg',
      '/images/textiles/gallery/activewear-grid/product-2.jpg',
      '/images/textiles/gallery/activewear-grid/product-3.jpg',
      '/images/textiles/gallery/activewear-grid/product-4.jpg',
      '/images/textiles/gallery/activewear-grid/product-5.jpg',
      '/images/textiles/gallery/activewear-grid/product-6.jpg',
      '/images/textiles/gallery/activewear-grid/product-7.jpg',
      '/images/textiles/gallery/activewear-grid/product-8.jpg',
    ],
    features: [
      { label: 'Method', text: 'One of the most technologically advanced production methods in fashion, made on specialised circular looms and Santoni machines.' },
      { label: 'Material', text: 'Soft, breathable seamless knits — typically under 10% spandex — built to stretch and recover without losing shape.' },
      { label: 'Sustainability', text: 'A more cost-effective, environmentally friendly process that uses less material, less time and produces less waste.' },
    ],
    statBanner: {
      image: '/images/textiles/banners/activewear.jpg',
      title: 'Seamless Technology',
      stat: 'Zero Cutting, Zero Sewing',
      description: 'Made on specialised circular looms in one continuous process — one of the most technologically advanced methods in fashion, producing less waste along the way.',
    },
    crossLinks: [
      { tag: 'Sustainability', title: 'Low-Waste by Design', description: 'See how our seamless, low-waste production supports GT Portugal\'s wider sustainability commitments.', href: '/sustainability' },
      { tag: 'Footwear', title: 'Complete the Look', description: 'Explore the sneakers and trainers we produce for the same activewear brands.', href: '/footwear' },
    ],
  },
  {
    slug: 'knitwear',
    image: '/images/textiles/knitwear.jpg',
    cardImage: '/images/textiles/original-thumbnails/knitwear.jpg',
    title: 'Knitwear',
    tagline: 'Timeless & Comfortable',
    cardDescription: 'From cosy sweaters to lightweight cardigans, GT Portugal is capable of creating a warm and comfortable knitwear collection.',
    description: 'From knitted roll-necks to lightweight cardigans, we prioritise warmth and comfort in every timeless piece — using jacquards, jerseys, felpa and rib in cotton, linen, silk, modal and cashmere.',
    gallery: [
      '/images/textiles/knitwear.jpg',
      '/images/textiles/gallery/knitwear-2.jpg',
      '/images/textiles/gallery/knitwear-3.jpg',
    ],
    productGrid: [
      '/images/textiles/gallery/knitwear-grid/product-1.jpg',
      '/images/textiles/gallery/knitwear-grid/product-2.jpg',
      '/images/textiles/gallery/knitwear-grid/product-3.jpg',
      '/images/textiles/gallery/knitwear-grid/product-4.jpg',
      '/images/textiles/gallery/knitwear-grid/product-5.jpg',
      '/images/textiles/gallery/knitwear-grid/product-6.jpg',
      '/images/textiles/gallery/knitwear-grid/product-7.jpg',
      '/images/textiles/gallery/knitwear-grid/product-8.jpg',
    ],
    features: [
      { label: 'Materials', text: 'Jacquards, jerseys, fleece, interlock and rib in cotton, linen, polyamide, polyester, modal, silk or cashmere.' },
      { label: 'MOQs', text: '300 pieces per style and colour, keeping quality and pricing consistent for our clients.' },
      { label: 'Production', text: '6 to 8 weeks to bring an idea to a finished, quality-checked piece.' },
    ],
    statBanner: {
      image: '/images/textiles/banners/knitwear.jpg',
      title: 'Fast Lead Time',
      stat: '6-8 Weeks',
      description: '300-piece MOQs per style and colour, with 6 to 8 weeks to bring an idea to a finished, quality-checked piece — keeping quality and pricing consistent for our clients.',
    },
    crossLinks: [
      { tag: 'About', title: '40+ Years of Craft', description: 'Learn about the story and process behind every knitted piece we produce.', href: '/about' },
      { tag: 'Sustainability', title: 'Responsible Production', description: 'Discover the certifications and renewable energy practices behind our knitwear.', href: '/sustainability' },
    ],
  },
  {
    slug: 'swimwear',
    image: '/images/textiles/swimwear.jpg',
    cardImage: '/images/textiles/original-thumbnails/swimwear.png',
    title: 'Swimwear',
    tagline: 'Nontoxic, Organic & UV Protected',
    cardDescription: 'A wide selection of eco-conscious swimwear, using the most trendy and innovative types of recycled fabrics for well-known international brands.',
    description: 'Nontoxic, organic and UV-protected — we produce swimwear using the most trend-forward recycled fabrics, balancing fit, durability and stretch for leading international brands.',
    productGridColumns: 5,
    gallery: [
      '/images/textiles/swimwear.jpg',
      '/images/textiles/gallery/swimwear-2.jpg',
      '/images/textiles/gallery/swimwear-3.jpg',
    ],
    productGrid: [
      '/images/textiles/gallery/swimwear-grid/product-1.jpg',
      '/images/textiles/gallery/swimwear-grid/product-2.jpg',
      '/images/textiles/gallery/swimwear-grid/product-3.jpg',
      '/images/textiles/gallery/swimwear-grid/product-4.jpg',
      '/images/textiles/gallery/swimwear-grid/product-5.jpg',
      '/images/textiles/gallery/swimwear-grid/product-6.jpg',
      '/images/textiles/gallery/swimwear-grid/product-7.jpg',
      '/images/textiles/gallery/swimwear-grid/product-8.jpg',
      '/images/textiles/gallery/swimwear-grid/product-9.jpg',
      '/images/textiles/gallery/swimwear-grid/product-10.jpg',
    ],
    features: [
      { label: 'Materials', text: 'Polyester, spandex and nylon blends, plus recycled fibres like ECONYL®, TENCEL and REPREVE.' },
      { label: 'Sustainability', text: 'Certified via the OEKO-Tex Standard 100 and registered with the Seaqual Initiative.' },
      { label: 'Lead Time', text: '4 weeks for sampling, up to 8 weeks for production — longer during peak summer season.' },
    ],
    statBanner: {
      image: '/images/textiles/banners/swimwear.jpg',
      title: 'Fast Lead Time',
      stat: '4-8 Weeks',
      description: 'Within this product category, our lead times for sampling are around the 4-week mark, while production usually takes up to 8 weeks after final sampling approval. As a seasonal product, peak times prior to summer season may generally mean higher lead times.',
    },
    crossLinks: [
      { tag: 'Sustainability', title: 'Certified Materials', description: 'ECONYL®, TENCEL and Seaqual — see the certifications behind our recycled swimwear fabrics.', href: '/sustainability' },
      { tag: 'Footwear', title: 'Complete the Collection', description: 'Pair your swimwear line with the sandals and slides from our footwear division.', href: '/footwear' },
    ],
  },
  {
    slug: 'outerwear',
    image: '/images/textiles/outerwear.jpg',
    cardImage: '/images/textiles/original-thumbnails/outerwear.png',
    title: 'Outerwear',
    tagline: 'Protective by Design',
    cardDescription: 'From raincoats, trench coats, jackets, basic leather coats, or bombers, we specialise in the art of outerwear making.',
    description: 'Raincoats, trench coats, jackets and bombers designed to handle the elements without compromising on style — made with long-lasting, easy-care fabrics that are recyclable, renewable and biodegradable.',
    gallery: [
      '/images/textiles/outerwear.jpg',
      '/images/textiles/gallery/outerwear-2.jpg',
      '/images/textiles/gallery/outerwear-3.jpg',
    ],
    productGrid: [
      '/images/textiles/gallery/outerwear-grid/product-1.jpg',
      '/images/textiles/gallery/outerwear-grid/product-2.jpg',
      '/images/textiles/gallery/outerwear-grid/product-3.jpg',
      '/images/textiles/gallery/outerwear-grid/product-4.jpg',
      '/images/textiles/gallery/outerwear-grid/product-5.jpg',
      '/images/textiles/gallery/outerwear-grid/product-6.jpg',
      '/images/textiles/gallery/outerwear-grid/product-7.jpg',
      '/images/textiles/gallery/outerwear-grid/product-8.jpg',
    ],
    features: [
      { label: 'Weather Protection', text: 'Engineered against wind, rain, snow and UV, with moisture-wicking and antibacterial properties.' },
      { label: 'Materials', text: 'Certified recyclable and biodegradable fabrics, including merino wool and Tencel Lyocell.' },
      { label: 'Range', text: 'Rain coats, bombers, parkas, trench coats, wool jackets and technical garments.' },
    ],
    statBanner: {
      image: '/images/textiles/banners/outerwear.jpg',
      title: 'Built to Protect',
      stat: '6 Key Factors',
      description: 'From wind, rain and UV resistance to moisture-wicking, antibacterial finishing and thermal insulation, every outerwear piece is engineered against six core performance factors.',
    },
    crossLinks: [
      { tag: 'About', title: 'Engineered Performance', description: 'Meet the team behind the weatherproofing and finishing that goes into every piece.', href: '/about' },
      { tag: 'Sustainability', title: 'Responsible Materials', description: 'Recyclable, renewable, biodegradable — our approach to responsible outerwear fabrics.', href: '/sustainability' },
    ],
  },
  {
    slug: 'soft-woven',
    image: '/images/textiles/softwoven.jpg',
    cardImage: '/images/textiles/original-thumbnails/soft-woven.jpg',
    title: 'Soft Woven',
    tagline: 'Stronger & Flexible',
    cardDescription: 'Tops, shirt, dresses and trousers made with woven fabrics. We have a large stock of woven fabrics, allowing you to bring your ideas to life faster.',
    description: 'Tops, shirts, dresses and trousers made from woven fabric — flexible, strong and shape-retaining. We specialise in flannels, poplin and gabardine.',
    gallery: [
      '/images/textiles/softwoven.jpg',
      '/images/textiles/gallery/soft-woven-2.jpg',
      '/images/textiles/gallery/soft-woven-3.jpg',
    ],
    productGrid: [
      '/images/textiles/gallery/soft-woven-grid/product-1.jpg',
      '/images/textiles/gallery/soft-woven-grid/product-2.jpg',
      '/images/textiles/gallery/soft-woven-grid/product-3.jpg',
      '/images/textiles/gallery/soft-woven-grid/product-4.jpg',
      '/images/textiles/gallery/soft-woven-grid/product-5.jpg',
      '/images/textiles/gallery/soft-woven-grid/product-6.jpg',
      '/images/textiles/gallery/soft-woven-grid/product-7.jpg',
      '/images/textiles/gallery/soft-woven-grid/product-8.jpg',
    ],
    features: [
      { label: 'Weave', text: 'Twill, satin and plain weave, each suited to a different look and application.' },
      { label: 'Specialisation', text: 'Yarn-dyed plaid flannels and alaska-quality overshirts; stock-service poplin.' },
      { label: 'Capacity', text: 'Up to 100K units in production capacity.' },
    ],
    statBanner: {
      image: '/images/textiles/banners/soft-woven.jpg',
      title: 'Production Capacity',
      stat: '100K Units',
      description: 'Backed by a large stock of woven fabrics and specialised flannel, poplin and gabardine expertise, so ideas move from concept to production fast.',
    },
    crossLinks: [
      { tag: 'About', title: 'Our Process', description: 'Learn about the people and process behind our flannel, poplin and gabardine expertise.', href: '/about' },
      { tag: 'Footwear', title: 'The Same Standard', description: 'See how the same quality standards carry through to our footwear production.', href: '/footwear' },
    ],
  },
  {
    slug: 'jersey',
    image: '/images/textiles/jersey.jpg',
    cardImage: '/images/textiles/original-thumbnails/jersey.jpg',
    title: 'Jersey',
    tagline: 'Cut, Sew & Sustainable',
    cardDescription: 'From jackets to dresses, from minimalistic looks to strong streetwear products full of embroideries, prints and washings, from high-definition jacquards to digital printed sweats.',
    description: 'Cut-and-sew knits produced across Portugal\'s most competitive textile cluster — from jackets to dresses, minimalist looks to streetwear full of embroidery, prints and washes.',
    gallery: [
      '/images/textiles/jersey.jpg',
      '/images/textiles/gallery/jersey-2.jpg',
      '/images/textiles/gallery/jersey-3.jpg',
    ],
    productGrid: [
      '/images/textiles/gallery/jersey-grid/product-1.jpg',
      '/images/textiles/gallery/jersey-grid/product-2.jpg',
      '/images/textiles/gallery/jersey-grid/product-3.jpg',
      '/images/textiles/gallery/jersey-grid/product-4.jpg',
      '/images/textiles/gallery/jersey-grid/product-5.jpg',
      '/images/textiles/gallery/jersey-grid/product-6.jpg',
      '/images/textiles/gallery/jersey-grid/product-7.jpg',
      '/images/textiles/gallery/jersey-grid/product-8.jpg',
    ],
    features: [
      { label: 'Network', text: 'A coordinated cluster of knitters, dyers, makers, embroiderers and printers, built on flexibility and expertise.' },
      { label: 'Sustainability', text: 'Produced in a country where over 50% of electricity comes from renewable sources.' },
      { label: 'Lead Time', text: '300-piece MOQs, with 6 to 9 weeks from concept to production.' },
    ],
    statBanner: {
      image: '/images/textiles/banners/jersey.jpg',
      title: 'MOQs & Lead Times',
      stat: '6-9 Weeks',
      description: '300-piece MOQs per style and colour, with 1 to 2 weeks for a stock-material prototype and 6 to 9 weeks from concept to full production.',
    },
    crossLinks: [
      { tag: 'Sustainability', title: 'Powered Responsibly', description: 'Portugal\'s renewable energy grid powers our jersey production — see our full sustainability approach.', href: '/sustainability' },
      { tag: 'About', title: 'A Coordinated Cluster', description: 'Knitters, dyers, makers and printers working as one — learn how GT Portugal brings it together.', href: '/about' },
    ],
  },
  {
    slug: 'denim',
    image: '/images/textiles/denim.jpg',
    cardImage: '/images/textiles/original-thumbnails/denim.jpg',
    title: 'Denim',
    tagline: 'A Timeless Fabric',
    cardDescription: 'From jackets to dresses, from minimalistic looks to strong streetwear products full of embroideries, prints and washings, from high-definition jacquards to digital printed sweats.',
    description: 'On the market since 1985 — a durable cotton twill fabric with a diagonal weave, produced using sustainable materials and finishes shaped by decades of technological innovation.',
    gallery: [
      '/images/textiles/denim.jpg',
      '/images/textiles/gallery/denim-2.jpg',
      '/images/textiles/gallery/denim-3.jpg',
    ],
    productGrid: [
      '/images/textiles/gallery/denim-grid/product-1.jpg',
      '/images/textiles/gallery/denim-grid/product-2.jpg',
      '/images/textiles/gallery/denim-grid/product-3.jpg',
      '/images/textiles/gallery/denim-grid/product-4.jpg',
    ],
    features: [
      { label: 'Process', text: 'From cotton selection and indigo dyeing to twill weaving, sanforizing and finishing treatments like stone-washing and distressing.' },
      { label: 'Sustainability', text: 'Produced in a country where over 50% of electricity comes from renewable sources.' },
      { label: 'Lead Time', text: '300-piece MOQs, with 6 to 9 weeks from concept to production.' },
    ],
    statBanner: {
      image: '/images/textiles/banners/denim.jpg',
      title: 'MOQs & Lead Times',
      stat: '6-9 Weeks',
      description: 'On the market since 1985 — 300-piece MOQs, 1 to 2 weeks for a prototype, and 6 to 9 weeks from concept to full production.',
    },
    crossLinks: [
      { tag: 'About', title: 'Four Decades of Denim', description: 'On the market since 1985 — discover the history and expertise behind GT Portugal.', href: '/about' },
      { tag: 'Sustainability', title: 'Powered Responsibly', description: 'See how renewable energy shapes responsible denim production at GT Portugal.', href: '/sustainability' },
    ],
  },
]

export function getCategory(slug) {
  return categories.find(c => c.slug === slug)
}

export function getRelatedCategories(slug, count = 4) {
  const startIndex = categories.findIndex(c => c.slug === slug)
  const rotated = [...categories.slice(startIndex + 1), ...categories.slice(0, startIndex)]
  return rotated.slice(0, count)
}
